version: '3'

volumes:
  db:
    driver: local

services:

# If you want to use mysql, un-comment this and comment the mariadb
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: 'dev'
#      MYSQL_USER: 'myuser'
#      MYSQL_PASSWORD: 'dev'
#      MYSQL_DATABASE: my_db
#      MYSQL_HOST: localhost
#    volumes:
#      - db:/var/lib/db
#    ports:
#      - 3030:3306

  db:
    image: mariadb:10-focal
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'dev'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'dev'
      MYSQL_DATABASE: my_db
      MYSQL_HOST: localhost
    volumes:
      - db:/var/lib/db
    ports:
      - 3030:3306

  php:
    build:
      context: build/silverstripe-php-7-1
    image: catharsisjelly/silverstripe-php:7.1-fpm
    restart: always
    environment:
      SS_DATABASE_CLASS: MySQLPDODatabase
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: dev
      SS_DATABASE_SERVER: db
      SS_DATABASE_NAME: my_db
      SS_DEFAULT_ADMIN_USERNAME: admin
      SS_DEFAULT_ADMIN_PASSWORD: admin
      SS_ENVIRONMENT_TYPE: dev
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  nginx:
    build:
      context: ./build/nginx
    image: catharsisjelly/nginx:stable
    restart: always
    ports:
      - 4430:443
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
      - db
